### PR TITLE
feat: add gradio demo notebook

### LINKED ISSUE #16: Gradio app notebook
A notebook to demonstrate how to build Gradio app with the model emitted from the Vertex Pipeline. The pipeline was run within my GCP project, there are two ways to test the model for you:

1. You run the pipeline on your own. To do this, you need to set a GitHub Secret of the GCP credential. The name of the GitHub Secret should be your `GCP PROJECT ID`. 
  - In this case, go to the `Action` tab, then select `Trigger Training Pipeline` section, then `Run workflow` with your own `GCP PROJET ID`.
  
2. Download a temporary model emitted from the Vertex Pipeline. The downloadable GCS Bucket can be found in `notebooks/inference_from_SavedModel.ipynb` notebook.

After this issue is done, we will work on porting this notebook to the standalone Gradio application.

### PR DESCRIPTION
**Pull request by sayakpaul**
Closes #16.

### CODE REVIEW

**Comment by deep-diver** [comment]
There are three things to comment:

1. Since we are going to inject which model to use from `🤗 Model Hub`, we need to reference a model hosted in `🤗 Model Hub`. I have prepared a test repository just now: https://huggingface.co/chansung/test-unet/tree/main.
    - It seems like we can leverate [`from_pretrained_keras`](https://github.com/huggingface/huggingface_hub/blob/b5d2d690683f2a278fd515fceaa9ccf08edd8668/src/huggingface_hub/keras_mixin.py) API from `huggingface_hug` package.

2. In order to generalize a bit, I think it could be better to make `labels.txt` file while removing `def sidewalk_palette()` from the code. 

3. It would be nice to include a couple of default images to run inference

WDYT?

**Comment by sayakpaul** [comment]
> In order to generalize a bit, I think it could be better to make labels.txt file while removing def sidewalk_palette() from the code.

Sure we can do that when writing code for the Hugging Face space. For a notebook that benefits from interactive usage, I think it would introduce unnecessary back and forth. 

I will address rest of the comments tomorrow.

**Comment by sayakpaul** [comment]
@deep-diver up for another review.

**Comment by deep-diver** [comment]
LGTM! Thanks for the great work :)

**Pull request merged**
